---
- name: Install Java
  hosts: all
  become: yes

  tasks:
  - name: Install aptitude
    apt: name=aptitude force_apt_get=yes

  - name: Install Oracle Java 8
    apt: name=openjdk-8-jre-headless state=present
