---
- name: Install Java
  hosts: all
  become: yes

  tasks:
  - name: Install aptitude
    apt: name=aptitude force_apt_get=yes
    
  - name: Updating repos
    apt: name=* state=latest

  - name: Install Java
    apt: name=openjdk-8-jre state=present
